export const LOAD_TRUCKS = "LOAD_TRUCKS"
export const LOAD_TRUCK = "LOAD_TRUCK"
export const CHANGE_ACTIVE_TRUCK_IMG = "CHANGE_ACTIVE_TRUCK_IMG"
export const FILTER_SEARCH_RESULTS = "FILTER_SEARCH_RESULTS"
